---
title: "Lineage Metrics Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load libraries
library(ggplot2)
library(readr)
library(reshape2)
library(dplyr)
library(scales)
```


This document contains all of the R code used to analyze data for this paper. The input csv files were generated from the raw data via Python scripts that are also included in this directory.

First let's read in the data:

```{r, message=FALSE}

theme_set(theme_classic())
theme_update(axis.title = element_text(size=18), axis.text = element_text(size=12), legend.text = element_text(size=14), legend.title = element_text(size=14), legend.position = "bottom", strip.text = element_text(size=18))


# Pull in two original data files and merge them tog
alex_real_value_data <- read_csv("../alex_real_value_data.csv")
emily_real_value_data <- read_csv("../real_value_data.csv")
real_value_data <- merge(alex_real_value_data, emily_real_value_data, all = TRUE)

# Convert problem and selection type codes to informative names. Convert things that should be factors to factors
real_value_data$problem <- sapply(as.character(real_value_data$p),switch,"0"="Himmelblau","1"="Six-hump camel back","2"="Shubert", "6"="Composition function 2")
real_value_data$problem <- as.factor(real_value_data$problem)
real_value_data$selection <- sapply(as.character(real_value_data$selection),switch,"0"="Tournament","1"="Lexicase","2"="Eco-EA", "3"="MAP-Elites", "4"="Roulette", "5"="Drift")
real_value_data$ts <- with(real_value_data, ifelse(selection=="Drift", 1, ts))
real_value_data$selection <- as.factor(real_value_data$selection)
real_value_data$seed <- as.factor(real_value_data$seed)
real_value_data$elite <- as.factor(real_value_data$elite)

# Grab the portion of data we're working with
tournament_data <- subset(real_value_data, (real_value_data$selection == "Tournament" | real_value_data$selection=="Drift") & real_value_data$elite == 0)
tournament_endpoints <- filter(tournament_data, update==5000)
tournament_endpoints$disp_pairwise_distance <- tournament_endpoints$variance_pairwise_distance/tournament_endpoints$mean_pairwise_distance
tournament_endpoints$disp_evo_distinct <- tournament_endpoints$variance_evolutionary_distinctiveness/tournament_endpoints$mean_evolutionary_distinctiveness

all_dom_data <- read_csv("~/repos/ALife2018-Lineage/analysis/cec_python_library/all_dom_data.csv")
all_dom_data$update <- 5000
all_dom_data$seed <- all_dom_data$RANDOM_SEED
all_dom_data$RANDOM_SEED <- NULL
all_dom_data$PROBLEM <- NULL
all_dom_data$DATA_DIRECTORY <- NULL
all_dom_data$RUN_MODE <- NULL
all_dom_data$path <- NULL

tournament_endpoints <- merge(tournament_endpoints, all_dom_data)
melted_tournament_data <- melt(tournament_endpoints, id.vars = c("update", "selection", "seed", "elite", "mutation_rate", "le", "p", "problem", "g", "ts", "TOURNAMENT_SIZE", "FITNESS_INTERVAL", "RESOURCE_SELECT__OUTFLOW", "MUTATION_STD", "SELECTION_METHOD", "RESOURCE_SELECT__RES_AMOUNT", "HINT_GRID_RES", "RESOURCE_SELECT__RES_INFLOW", "LEXICASE_EPSILON", "SYSTEMATICS_INTERVAL", "RESOURCE_SELECT__FRAC", "RESOURCE_SELECT__COST", "RESOURCE_SELECT__MAX_BONUS", "POP_SNAPSHOT_INTERVAL", "POP_SIZE", "ELITE_SELECT__ELITE_CNT", "GENERATIONS"))
end_points_vars_of_interest <- melted_tournament_data %>%  filter(variable %in% c("mrca_depth", "dominant_deleterious_steps", "current_phylogenetic_diversity", "mean_pairwise_distance", "phenotypic_volatility", "total_magnitude"))

labels <- c(current_phylogenetic_diversity = "Phylogenetic diversity", dominant_deleterious_steps = "Deleterious steps", mean_evolutionary_distinctiveness="Mean evo. distinctiveness", mean_pairwise_distance="Mean pairwise distance", mrca_depth="MRCA depth", variance_evolutionary_distinctiveness="Variance evo. distinctiveness", variance_pairwise_distance = "Variance pairwise distance", phenotypic_volatility="Phenotypic volatility", total_magnitude="Mutation accumulation")


```

```{r}
ggplot(subset(end_points_vars_of_interest, end_points_vars_of_interest$mutation_rate==.001), aes(x=ts, y=value, fill=problem, color=problem, group=problem)) + stat_summary(fun.y = median, fun.ymin = function(x){quantile(x)[2]}, fun.ymax=function(x){quantile(x)[4]}) +stat_summary(geom="smooth", fun.data="mean_cl_boot")+ theme_classic() + scale_x_log10("Tournament size", breaks=c(1,2,4,8,16)) + scale_y_log10("", labels=scientific, breaks = scales::trans_breaks("log10", function(x) 10^x)) + facet_wrap(~variable, scales="free_y", labeller = labeller(variable=labels),ncol=2) + scale_color_discrete("Problem") + theme(legend.position = "bottom", legend.title = element_text(size=10), legend.text = element_text(size=6), strip.text = element_text(size=6), axis.text = element_text(size=6)) + guides(color=guide_legend(ncol=2), fill="none")
ggsave("../figs/all_ts.png", width=3.5, height=4.5) 
```


```{r}
ggplot(subset(end_points_vars_of_interest, end_points_vars_of_interest$ts==4), aes(x=mutation_rate, y=value, fill=problem, color=problem)) + stat_summary(fun.y = median, fun.ymin = function(x){quantile(x)[2]}, fun.ymax=function(x){quantile(x)[4]}) +stat_summary(geom="smooth", fun.data="mean_cl_boot")+ theme_classic() + scale_x_log10("Mutation rate", labels=scientific) + scale_y_log10("", breaks = scales::trans_breaks("log10", function(x) 10^x), labels=scientific) + facet_wrap(~variable, scales="free_y", labeller = labeller(variable=labels), ncol=2) +scale_color_discrete("Problem") + theme(legend.position = "bottom", legend.title = element_text(size=10), legend.text = element_text(size=6), strip.text = element_text(size=6), axis.text = element_text(size=6)) + guides(color=guide_legend(ncol=2), fill="none")
ggsave("../figs/all_mutation_rate.png", width=3.5, height=4.5)

```

```{r}
#Coexistence figure

# Grab the portion of data we're working with
eco_ea_data <- subset(real_value_data, real_value_data$selection == "Eco-EA" & real_value_data$elite == 1)
eco_ea_endpoints <- filter(eco_ea_data, update==5000)
eco_ea_endpoints$disp_pairwise_distance <- eco_ea_endpoints$variance_pairwise_distance/eco_ea_endpoints$mean_pairwise_distance
eco_ea_endpoints$disp_evo_distinct <- eco_ea_endpoints$variance_evolutionary_distinctiveness/eco_ea_endpoints$mean_evolutionary_distinctiveness

eco_ea_endpoints <- merge(eco_ea_endpoints, all_dom_data)
melted_eco_ea_data <- melt(eco_ea_endpoints, id.vars = c("update", "selection", "seed", "elite", "mutation_rate", "le", "p", "problem", "g", "ts", "TOURNAMENT_SIZE", "FITNESS_INTERVAL", "RESOURCE_SELECT__OUTFLOW", "MUTATION_STD", "SELECTION_METHOD", "RESOURCE_SELECT__RES_AMOUNT", "HINT_GRID_RES", "RESOURCE_SELECT__RES_INFLOW", "LEXICASE_EPSILON", "SYSTEMATICS_INTERVAL", "RESOURCE_SELECT__FRAC", "RESOURCE_SELECT__COST", "RESOURCE_SELECT__MAX_BONUS", "POP_SNAPSHOT_INTERVAL", "POP_SIZE", "ELITE_SELECT__ELITE_CNT", "GENERATIONS"))
eco_ea_vars_of_interest <- melted_eco_ea_data %>%  filter(variable %in% c("mrca_depth", "dominant_deleterious_steps", "current_phylogenetic_diversity", "mean_pairwise_distance", "phenotypic_volatility", "total_magnitude"))

ggplot(eco_ea_vars_of_interest, aes(x=mutation_rate, y=value, fill=problem, color=problem, group=problem)) + stat_summary(fun.y = median, fun.ymin = function(x){quantile(x)[2]}, fun.ymax=function(x){quantile(x)[4]}) +stat_summary(geom="smooth", fun.data="mean_cl_boot")+ theme_classic() + scale_x_log10("Mutation rate") + scale_y_log10("", labels=scientific, breaks = scales::trans_breaks("log10", function(x) 10^x)) + facet_wrap(~variable, scales="free_y", labeller = labeller(variable=labels),ncol=2) + scale_color_discrete("Problem") + theme(legend.position = "bottom", legend.title = element_text(size=10), legend.text = element_text(size=6), strip.text = element_text(size=6), axis.text = element_text(size=6)) + guides(color=guide_legend(ncol=2), fill="none")
ggsave("../figs/eco_mutation_rate.png", width=3.5, height=4.5)

```

# Avida

```{r}
library(readr)
all_data <- read_csv("../data/all_data.csv")
endpoints <- filter(all_data, update==200000)
melted_endpoints <- melt(endpoints, id.vars=c("update", "environment", "rep"))
melted_endpoints$value <- as.numeric(as.character(melted_endpoints$value))
melted_endpoints$environment <- as.factor(melted_endpoints$environment)
endpoints_of_interest <- melted_endpoints %>% filter (variable %in% c("mrca_depth", "dominant_deleterious_steps", "current_phylogenetic_diversity", "mean_pairwise_distance", "diversity", "generation", "ave_depth", "variance_pairwise_distance", "mean_evolutionary_distinctiveness","mean_deleterious_steps", "variance_deleterious_steps", "mean_taxon_volatility", "mean_unique_taxa", "dominant_unique_phenotypes", "dominant_lineage_length", "dominant_deleterious_steps", "dominant_phenotypic_volatility", "gestation", "num_taxa"))
ggplot(endpoints_of_interest, aes(x=environment, y=value, fill=environment, group=environment)) + geom_boxplot() + facet_wrap(~variable, scales="free_y")

```

```{r}
library(readr)
gen_endpoints <- all_data %>% group_by(rep, environment) %>% by_slice(~ slice(.,detect_index(.$generation, ~ .x >= 10000)), .collate = "rows")
melted_endpoints_gen <- melt(gen_endpoints, id.vars=c("generation", "environment", "rep"))
melted_endpoints_gen$value <- as.numeric(as.character(melted_endpoints_gen$value))
melted_endpoints_gen$environment <- as.factor(melted_endpoints_gen$environment)
#endpoints_of_interest_gen <- melted_endpoints_gen %>% filter (variable %in% c("mrca_depth", "dominant_deleterious_steps", "current_phylogenetic_diversity", "mean_pairwise_distance", "diversity", "generation", "ave_depth", "variance_pairwise_distance", "mean_evolutionary_distinctiveness","mean_deleterious_steps", "variance_deleterious_steps", "mean_taxon_volatility", "mean_unique_taxa", "dominant_unique_phenotypes", "dominant_lineage_length", "dominant_deleterious_steps", "dominant_phenotypic_volatility", "gestation", "num_taxa"))
endpoints_of_interest_gen <- melted_endpoints_gen %>% filter (variable %in% c("mrca_depth", "mean_unqiue_taxa", "mean_pairwise_distance"))

ggplot(endpoints_of_interest_gen, aes(x=environment, y=value, fill=environment, group=environment)) + geom_boxplot() + facet_wrap(~variable, scales="free_y")

```
```{r}
# Extract relevant data from CSV
seq_data <- read_csv("../data/lineage_sequences.csv", 
                      col_types=cols_only(treatment=col_character(),
                                          run_id=col_character(),
                                          pull_condition=col_character(),
                                          max_update=col_integer(),
                                          total_muts=col_integer(),
                                          total_substitutions=col_integer(),
                                          total_insertions=col_integer(),
                                          total_deletions=col_integer(),
                                          phen_seq_by_geno_unique_state_cnt=col_integer(),
                                          phen_seq_by_geno_length=col_integer(),
                                          phen_seq_by_geno_volatility=col_integer(),
                                          phen_seq_by_geno_avg_state_duration=col_double(),
                                          phen_seq_by_geno_state_duration_variance=col_double(),
                                          phen_seq_by_phen_unique_state_cnt=col_integer(),
                                          phen_seq_by_phen_length=col_integer(),
                                          phen_seq_by_phen_volatility=col_integer(),
                                          phen_seq_by_phen_avg_state_duration=col_double(),
                                          phen_seq_by_pheno_state_duration_variance=col_double())
)

# Separate generation 10k data and update 200k data
generation_data <- filter(seq_data, pull_condition == "gen-10000")
update_data <- filter(seq_data, pull_condition == "update-200000")

generation_data <- generation_data %>% mutate(total_substitutions = total_substitutions/total_muts, total_deletions = total_deletions/total_muts, total_insertions = total_insertions/total_muts)

melted_generation_data <- melt(generation_data, id.vars=c("treatment", "run_id", "pull_condition", "max_update"))
gens_vars_of_interest <- melted_generation_data %>% filter(variable %in% c("phen_seq_by_phen_unique_state_cnt","phen_seq_by_phen_length","phen_seq_by_phen_volatility","phen_seq_by_phen_avg_state_duration"))

gens_vars_of_interest_mut <- melted_generation_data %>% filter(variable %in% c("total_muts", "total_substitutions", "total_insertions", "total_deletions"))

gens_vars_of_interest_mut_labeled <- gens_vars_of_interest %>% transform(variable = case_when(variable == "total_muts" ~ "Count of all mutations", variable=="total_substitutions" ~ "Proportion of substitutions", variable=="total_insertions" ~ "Proportion of insertions", variable == "total_deletions" ~ "Proportion of deletions")) %>% transform(treatment = case_when(treatment == "change" ~ "Changing", treatment == "empty" ~ "Minimal", treatment == "l9" ~ "Logic-9", treatment == "limres" ~ "Limited\nresources"))

# Plot by generations
ggplot(gens_vars_of_interest_mut_labeled, aes(x=treatment, y=value, fill=treatment, color=treatment, group=treatment)) + facet_wrap(~variable, scales="free") + geom_boxplot(color="black") + scale_y_continuous("") + theme(legend.position = "none") + scale_x_discrete("Treatment")
ggsave("mutations_avida.png")

```

### Muller plots

```{r}
library(ggmuller)
library(readr)

limres21_adjacency <- read_csv("../data/limres21_adjacency.csv")
limres21_pop_info <- read_csv("../data/limres21_pop_info.csv")
limres21_adjacency <- limres21_adjacency[c("Parent", "Identity")]


limres21_pop_info_trunc <- filter(limres21_pop_info, Time < 8000000)

limres_Muller_df_trunc <- get_Muller_df(limres21_adjacency, limres21_pop_info_trunc, cutoff = .05)
limres_Muller_df_trunc <- filter(limres_Muller_df_trunc, Time < 8000000)
fits <- limres_Muller_df_trunc %>% group_by(Identity) %>% summarize(Phenotype = max(Phenotype, na.rm = TRUE))
correct_df <- left_join(limres_Muller_df_trunc %>% select(-one_of("Fitness"), -one_of("Phenotype")), fits)

Muller_plot(correct_df, colour_by = "Phenotype")

```